analyse_hospitals:
  description: >
    Read a list of hospital units from the json file {json_file}.
  expected_output: >
    A structured output with a list of hospitals with their unique id, the x_coordinate and y_coordinate
  agent: analyser_agent

assign_hospitals:
  description: >
    Take the response from the analyser_agent.
    For every unit of hospitals in the updated list calculate its distance from the emergency event to the hospital using the RouteDistanceTool.
    Pass to the tool as x_origin, y_origin the coordinates of the hospital and as x_destination, y_destination the coordinates of the emergency event (x={x_location}, y={y_location}).
    Return the id of the hospital unit that has the smaller distance to the fire event and the distance computed with the RouteDistanceTool.
  expected_output: >
    A structured output with the selected id of the hospital and the distance computed with the RouteDistanceTool
  agent: rescue_agent